#!/usr/bin/python3

try:

	from random import choice
	from os import system
	print('Knack den Code Version 1.0.00')
	while True:
		text=choice(["I_h b?? C??l. \nH??t?e g?he i?h b?d?n.","F__b?l? i?t e?? S?o?t m?t ??nem B??l. \n d?r S??rt ??t f?? J??gs.","M__ ??t?? k??n m?? fa??en. D?? ???? Sp?? m???en."])

		if text=="I_h b?? C??l. \nH??t?e g?he i?h b?d?n.":
			print(text)
			text=input('Was ist der eine Buchstabe in der "_"-Lücke? > ')

			while not text=='c':
				print('Falsch')
				text=input('Was ist der eine Buchstabe in der "_"-Lücke? > ')

			print('Richtig!')
			text=print('Ich b__ C??l.\nH??t? g?he i?h b?d?n.')
			text=input('Was sind die zwei Buchstaben in der "_"-Lücke? > ')

			while not text=="in":
				print("Falsch")
				text=print('Ich b__ C??l.\nH??t? g?he i?h b?d?n.')
				text=input('Was sind die zwei Buchstaben in der "_"-Lücke? > ')
			print('Richtig')
			text=print('Ich bin C__l.\nH??t? g?he i?h b?d?n.')
			text=input('Was sind die zwei Buchstaben in der "_"-Lücke? > ')
			while not text=="oo":
				print('Falsch!')
				text=print('Ich bin C__l.\nH??t? g?he i?h b?d?n.')
				text=input('Was sind die zwei Buchstaben in der "_"-Lücke? > ')
			print('Richtig!')
			text=print('Ich bin Cool.\nH__t? g?he i?h b?d?n.')
			text=input('Was sind die zwei Buchstaben in der "_"-Lücke? > ')
			while not text=="eu":
				print('Falsch')
				text=print('Ich bin Cool.\nH__t? g?he i?h b?d?n.')
				text=input('Was sind die zwei Buchstaben in der "_"-Lücke? > ')
			print('Richtig!')
			text=print('Ich bin Cool.\nHeut_ g?he i?h b?d?n.')
			text=input('Was ist der Buchstabe in der "_"-Lücke? > ')
			while not text=='e':
				print('Falsch!')
				text=print('Ich bin Cool.\nHeut_ g?he i?h b?d?n.')
				text=input('Was ist der Buchstabe in der "_"-Lücke? > ')
			print('Richtig!')
			text=print('Ich bin Cool.\nHeute g_he i?h b?d?n.')
			text=input('Was ist der Buchstabe in der "_"-Lücke? > ')
			while not text=='e':
				print('Falsch!')
				text=print('Ich bin Cool.\nHeute g_he i?h b?d?n.')
				text=input('Was ist der Buchstabe in der "_"-Lücke? > ')
			print('Richtig!')
			text=print('Ich bin Cool.\nHeute gehe i_h b?d?n.')
			text=input('Was ist der Buchstabe in der "_"-Lücke? > ')
			while not text=='c':
				print('Falsch!')
				text=print('Ich bin Cool.\nHeute gehe i_h b?d?n.')
			text=input('Was ist der Buchstabe in der "_"-Lücke? > ')
			print('Richtig!')
			text=print('Ich bin Cool.\nHeute gehe ich b_d?n.')
			text=input('Was ist der Buchstabe in der "_"-Lücke? > ')
			while not text=="a":
				print('Falsch!')
				text=print('Ich bin Cool.\nHeute gehe ich b_d?n.')
				text=input('Was ist der Buchstabe in der "_"-Lücke? > ')
			print('Richtig!')
			text=print('Ich bin Cool.\nHeute gehe ich bad_n.')
			text=input('Was ist der Buchstabe in der "_"-Lücke? > ')
			while not text=="e":
				print('Falsch!')
				text=print('Ich bin Cool.\nHeute gehe ich bad_n.')
				text=input('Was ist der Buchstabe in der "_"-Lücke? > ')
			print('SUPER!')
			print('Du hast den Text erraten!')
			text=print('Ich bin Cool.\nHeute gehe ich baden.')
			print('Mach weiter so.')
	if text=="F__b?l? i?t e?? S?o?t m?t ??nem B??l. \n d?r S??rt ??t f?? J??gs.":
		text=input('Lücke bitte mit 3 Buchstaben ausfüllen > ')
		while not text=='uß':
			print('Falsch!')
			text=input('Lücke bitte mit 3 Buchstaben ausfüllen > ')
			choice(["Schön!","Gut","Passt!"]) | print



except KeyboardInterrupt:
	print('Bis Bald!')

except EOFError:
	pass
except KeyboardInterrupt:
	pass