#!/bin/python3

"""
Was ich machen will:
- Er soll eine Zeile aus der Datei von Argument 1 eine Zeile auswählen
- Er soll Kürzel für jeden Buchstaben erstellen 
"""
import random,re
import argparse
import os
import sys
parser = argparse.ArgumentParser(description='Ein Knack-Den-Code Programm')
parser.add_argument('--file', required=True, help='Datei zum auswählen von einer Zeile')
#parser.add_argument('--value', required=True, default="[echo.v] Fehler: Argument --value erforderlich", help='Text in Anführungszeichen ("") angeben')
args = parser.parse_args()

with open(args.file) as datei:
	liste=datei.read().strip().split("\n")
	text=random.choice(liste)

# hübsche den text auf (von Papa)
text=re.sub(r"([!?.]) ",r"\1\n",text).strip()
text="\n".join([ f"{nr+1}: {line}" for nr,line in enumerate(text.split("\n"))])

#code_zu_zeichen={"ü":"a","ö":"b","ä":"c","z":"d","y":"e","x":"f","w":"g","v":"h","u":"i","t":"j","s":"k","r":"l","q":"m","p":"n","o":"o","n":"p","m":"q","l":"r","k":"s","j":"t","i":"u","h":"v","w":"g","f":"x","e":"y","d":"z","ä":"c","ö":"b","ü":"a"}
alphabet=["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z","ä","ö","ü","ß"]
codes=["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z","ä","ö","ü","ß"]
random.shuffle(codes)

anzahl_codes=len(codes)
code_zu_zeichen={}
for i in range(anzahl_codes):
	#code_zu_zeichen={f'"{alphabet[i]}":"{codes[i]}"'}
	code=codes[i]
	code_zu_zeichen[code]=alphabet[i]

zeichen_zu_code={}
for code in code_zu_zeichen:
	zeichen=code_zu_zeichen[code]
	zeichen_zu_code[zeichen]=code

kodierter_text=""
dekodierter_text=f""
minuse=f""
anzahl_zeichen=0
for zeichen in text:
	anzahl_zeichen=anzahl_zeichen+1
	code=zeichen
	if zeichen in zeichen_zu_code:
		code=zeichen_zu_code[zeichen]
	elif zeichen.lower() in zeichen_zu_code:
		code=zeichen_zu_code[zeichen.lower()]
		code=code.upper()
		#sys.stdout.write
	kodierter_text=kodierter_text+code
	wert=f""
	if zeichen in alphabet:
		wert="_"
	elif zeichen.lower() in alphabet:
		wert="_"
	else:
		wert=zeichen
	
	
	
	dekodierter_text=dekodierter_text+wert
	#minuse=minuse+"-"
	minuse+="-"

#print(f"Es wurde ein Code erzeugt zur einer Zeile in der Angegebenen Datei: {args.file}\n\n{kodierter_text}")
print(f"\nKnack-den-Code Version 2")
erkannt=0
fehler=0
versuche=0
richtig=0
while not dekodierter_text==text:
	try:
		print(f"\nAktueller Status:\n\nVersuche: {versuche}\nErkannte Buchstaben: {erkannt} von {anzahl_zeichen}\nVersuche mit Erfolg: {richtig}\nFehlversuche: {fehler}\n\n\n\n{dekodierter_text}\n\n{kodierter_text}\n\nGib nun einen Codebuchstaben und den richtigen Buchstaben ein. Beispiel: <Code>=<Buchstabe>\nIn diesem Text befinden sich {anzahl_zeichen} Zeichen.")
		value=input("Eingabe: ")
		versuche=versuche+1
		if "=" in value:
			liste=value.split("=")
			#print(liste)
			code=liste[0].lower().strip()
			zeichen=liste[1].lower().strip()

			if code in code_zu_zeichen and code_zu_zeichen[code]==zeichen:
				
				#neues_i=[]
				for i in range(anzahl_zeichen):
					#neues_i=neues_i+i
					#print(neues_i[0])
					#print(text[i])
					#print(dekodierter_text[i])
					if kodierter_text[i]==code:
						erkannt=erkannt+1
						dekodierter_text=dekodierter_text[0:i]+zeichen+dekodierter_text[i+1:]
					if kodierter_text[i]==code.upper():
						erkannt=erkannt+1
						dekodierter_text=dekodierter_text[0:i]+zeichen.upper()+dekodierter_text[i+1:]
				
				print("Richtig geraten!")
				richtig=richtig+1
			else:
				print("Falsch geraten!")
				fehler=fehler+1
	except KeyboardInterrupt as e:
		print("\nSkript kann wegen einer unerwarteten Unterbrechung nicht fortgesetzt werden.\nFehlercode: 2\nTschüssi.\n")
		exit(2)
	except EOFError as e:
		print("\nSkript kann wegen einer unerwarteten Unterbrechung nicht fortgesetzt werden.\nFehlercode: 1\nTschüssi.\n")
		exit(1)
	except Exception:
		pass

print(f"SUPER! Du bist fertig!\n\nVersuche: {versuche}\nErkannte Buchstaben: {erkannt}\nVersuche mit Erfolg: {richtig}\nFehlversuche: {fehler}\n\nDein Text: \n{dekodierter_text}")